### ISSUE TITLE
Extensions not persistent

### ISSUE THREAD

**Issue by bambuleee** [PlusMinus0/headless-jd2-docker#13]
I installed the extension "folderwatch".
After pulling a  new image version and starting a new container (config path is the same), I have to reinstall folder watch.
Accounts etc are saved correctly.

**Comment by PlusMinus0** [comment]
Try ` -v /config/jd2:/opt/JDownloader \` instead of ` -v /config/jd2:/opt/JDownloader/cfg \`. This should keep the whole folder persisten.
