### ISSUE TITLE
[question] It is possible to run this docker on raspberry pi osmc?

### ISSUE THREAD

**Issue by atiris** [PlusMinus0/headless-jd2-docker#14]
Hi, I have raspberry pi running `Kodi` (on `osmc` system, so no Raspbian installed).  
Can I use this Docker to run JDownloader on such a configuration?

**I tried:**

- installing directly without modification

`sudo su`  
`mkdir /home/osmc/.config/jd2`  
`docker run -d --name jd2 -v /home/osmc/.config/jd2:/opt/JDownloader/cfg -v /home/osmc/Download:/downloads plusminus/jdownloader2-headless`  
`docker stop jd2`  
`nano /home/osmc/.config/jd2/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json`  

    { "email" : "myemail@host.host", "password" : "mypassword" }

`docker start jd2`
But this exits after about 4 seconds and in log there is:  _standard_init_linux.go:190: exec user process caused "exec format error"_

- running Dockerfile local:

Based on [this comment](https://github.com/PlusMinus0/headless-jd2-docker/issues/3#issuecomment-281639324) I copy Dockerfile and startJD2.sh from comment to one directory (but I tried it also without copying a file from another branch) and run this:  
`sudo docker build -f /home/osmc/Dockers/jd2/Dockerfile` and then `docker run`.  
Log: [local.txt](https://github.com/PlusMinus0/headless-jd2-docker/files/2048021/local.txt) **Result:**  

_Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--name\": executable file not found in $PATH": unknown._

Is it possible to run this and I am doing some mistake, or is this docker not designed for such a configuration?  
Many thanks for reply.

**Comment by PlusMinus0** [comment]
I don't think it's possible. I looked into it a while ago but never finished it. Check the Dockerfile in branch [rpi-test](https://github.com/PlusMinus0/headless-jd2-docker/tree/rpi-test) for a possible solution.

Cheers
