### ISSUE TITLE
Non-root setup broken

### ISSUE THREAD

**Issue by xduseko** [PlusMinus0/headless-jd2-docker#17]
Last version published is broken. It is not possible to make non-root setup.

```
jdownloader    | /opt/JDownloader/startJD2.sh: line 6: groupadd: command not found
jdownloader    | /opt/JDownloader/startJD2.sh: line 14: useradd: command not found
jdownloader    | /opt/JDownloader/startJD2.sh: line 19: useradd: command not found
jdownloader    | chown: unknown user/group jdownloader:jdownloader
```

Also it would be nice to start using tags so I can revert to older one. Right now only the latest is available.

**Comment by xduseko** [comment]
Added PR

**Comment by PlusMinus0** [comment]
Oh I'm sorry. Will merge later and look into tags. Thanks for the PR.

Cheers

**Comment by dannotdan** [comment]
Sorry for my GitHub ignorance, but I am either reading this wrong or pulling it wrong. It looks like the issue was fixed here a couple weeks ago but the Docker pull command still installs the broken version.
