### ISSUE TITLE
Credentials get overwritten in org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json

### ISSUE THREAD

**Issue by FiReiSFuN** [PlusMinus0/headless-jd2-docker#2]
I've followed the instructions - stopped the container, entered my credentials in org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json, then started the container. 

My jd2 instance doesn't show up on my.jdownloader.org. If I check org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json, my credentials have been overwritten and "null" is in their place. 

Any idea what's wrong?

**Comment by PlusMinus0** [comment]
Did you check the file again bevor restarting the container?

**Comment by SergioRius** [comment]
Same here.
Yes, I did check it and edited with the container being down, before restarting it.

**Comment by SergioRius** [comment]
It's working for me. The two things I made where executing chmod 664 * in the config folder and putting the credentials info between quotes. Seems that the last one could be what ade the trick.
If it's the case, it could be good to explicitly tell to do so in the readme.

**Comment by PlusMinus0** [comment]
@SergioRius you mean using quotes? If so, I'll add it.

**Comment by Stevethebeef** [comment]
Quotes will fix the issue!
Thanks guys
