### ISSUE TITLE
Doesn't work on OMV 4?

### ISSUE THREAD

**Issue by Weissnimma** [PlusMinus0/headless-jd2-docker#22]
Tried for many hours to start it, but without success.
The file "org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json" doesn't appear anywhere, creating the file doesn't help either. There are 22 files in the config directory, no subdirectory. 
When I start startJD2.sh, the following message appears:

adduser: user 'root' in use
chown: /opt/JDownloader/cfg/jd.controlling.linkcollector.LinkCollectorConfig.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.settings.GeneralSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.controlling.packagizer.PackagizerSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.api.RemoteAPIConfig.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.gui.views.linkgrabber.addlinksdialog.LinkgrabberSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/org.appwork.utils.logging2.LogConfig.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.settings.InternetConnectionSettings.customproxylist.json: Read-only file system
chown: /opt/JDownloader/cfg/startJD2.sh: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.updatev2.UpdateSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/jd.controlling.downloadcontroller.DownloadControllerConfig.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/jd.controlling.linkcrawler.LinkCrawlerConfig.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.update.lastchance.LastChanceConfig.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.settings.InternetConnectionSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/jd.controlling.reconnect.ReconnectConfig.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.settings.GeneralSettings.browsercommandline.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.settings.GeneralSettings.domainrules.json: Read-only file system
chown: /opt/JDownloader/cfg/ProxySelector.proxies.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.settings.GraphicalUserInterfaceSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/jd.controlling.captcha.CaptchaSettings.qualityensurancerules.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.settings.SilentModeSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/jd.controlling.captcha.CaptchaSettings.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.deviceconnectports.json: Read-only file system
chown: /opt/JDownloader/cfg/org.jdownloader.controlling.packagizer.PackagizerSettings.rulelist.json: Read-only file system
chown: /opt/JDownloader/cfg: Read-only file system
chown: /opt/JDownloader/cfg: Read-only file system
Usage: su-exec user-spec command [args]

**Comment by PlusMinus0** [comment]
What did you try to get it working. I don’t see why it shouldn’t work.

**Comment by kvn1351** [comment]
Works for me on OMV4 by assigning PUID and PGID correctly.

**Comment by PlusMinus0** [comment]
@Weissnimma ?

**Comment by Weissnimma** [comment]
Sorry about not answering. It is now running, but I don't know exactly why :) Thanks for the help!
