### ISSUE TITLE
Permission denied on Synology

### ISSUE THREAD

**Issue by kichetof** [PlusMinus0/headless-jd2-docker#25]
Hi guys,

Unable to run after update _(docker on Synology)_. At every launch, permissions are set to 1000 without considering env vars UID/GID.

Operator `-n` return : ` True if the length of string is nonzero.`
https://github.com/PlusMinus0/headless-jd2-docker/blob/e4cf08ec3c67333bf704683be44e13e4711bc200/common/entrypoint.sh#L4
https://github.com/PlusMinus0/headless-jd2-docker/blob/e4cf08ec3c67333bf704683be44e13e4711bc200/common/entrypoint.sh#L5

In my case, replace `-n ..` by `! -n ..` works fine.
I'm not 100% sure with this workaround, that's why I don't wrote a PR.

Thanks for your great container!!
Cheers

**Comment by PlusMinus0** [comment]
You are right. I used `-z` instead but that should fix it, added a test to confirm. Will merge as soon as travis is done.
