### ISSUE TITLE
Can't find *.json

### ISSUE THREAD

**Issue by Melf11** [PlusMinus0/headless-jd2-docker#3]
Actually is it possible to install on RPi3 with Libreelec installed? They got Docker Support on board now. I'm able to install your headless docker but i can't find the *.json config file anywhere. If i just create one with nano nothing happening.
Would be so nice, if it's possible

**Comment by PlusMinus0** [comment]
Did you run it once?

**Comment by Melf11** [comment]
yes, i did "docker start jd2" and than "docker stop jd2", and after that i tried to find the *,json in the folder which i selected for config and its emtpy

**Comment by Melf11** [comment]
here is my terminal:

```
LibreELEC:~/JDownloader2/config # docker run -d --name jd2 -v /storage/JDownloader2/config:/
opt/JDownloader/cfg -v /media/Ext_Black/JDownloads:/root/Downloads plusminus/jdownloader2-he
adless
c0132a9fc8daca52a20430c1cb9db6583194b3d2f30c335d3a85a4e0d7f6771b
LibreELEC:~/JDownloader2/config # docker stop jd2
jd2
LibreELEC:~/JDownloader2/config # ls
LibreELEC:~/JDownloader2/config # 
```

**Comment by PlusMinus0** [comment]
Looks like you're in the wrong folder. What's the output of `ls /storage/JDownloader2/config`
?

**Comment by Melf11** [comment]
is empty

**Comment by PlusMinus0** [comment]
Could you paste the output of `docker logs -t --tail 200 jd2` ?

**Comment by Melf11** [comment]
`LibreELEC:~/JDownloader2/config # docker logs -t --tail 200 jd2
2017-02-21T12:09:13.616130000Z standard_init_linux.go:178: exec user process caused "exec format error"
2017-02-21T12:28:57.917243000Z standard_init_linux.go:178: exec user process caused "exec format error"`

**Comment by PlusMinus0** [comment]
That seems to be a problem with your docker environment or with the java:jre container I'm using. Have you tried other containers?

**Comment by Melf11** [comment]
other dockers from the docker repository are working, but your docker is the first i tried

**Comment by PlusMinus0** [comment]
I switched bases and the new image should be done compiling, please give it a try.

**Comment by Melf11** [comment]
still the same problem. I installed now the Portainer Docker, and it works great. Than deleted all previous jd2 dockers and reinstalled it. 
I can run jd2, but i don't receive a *.json and in log is the same failure.

**Comment by PlusMinus0** [comment]
Weird. Could you try [this](https://github.com/PlusMinus0/headless-jd2-docker/blob/rpi-test/Dockerfile) Docker file?

**Comment by Melf11** [comment]
no, sorry, still the same problem. i removed the container and image and did a new pull, and got the same

**Comment by PlusMinus0** [comment]
Don't pull, build the Dockerfile from my last comment and run a container from it.

**Comment by Melf11** [comment]
ok, how can i do that? i'm really new in dockers.

**Comment by PlusMinus0** [comment]
https://docs.docker.com/engine/getstarted/step_four/

**Comment by Melf11** [comment]
hmm..propably i'm making mistakes:

```
LibreELEC:~/mydockerbuild # ls
Dockerfile
LibreELEC:~/mydockerbuild # docker build -t plusminus/jdownloader2-headless .
Sending build context to Docker daemon  2.56 kB
Error response from daemon: Unknown instruction: --PROGRESS=BAR:FORCE
LibreELEC:~/mydockerbuild # 
```

**Comment by PlusMinus0** [comment]
Remove --PROGRESS=BAR:FORCE from the Dockerfile

**Comment by Melf11** [comment]
ok i got it done, but it won't work. still can't start jd2

 ```
[...]
---> c3b6278957da
Removing intermediate container 9c1a0a774a9b
Step 4/6 : COPY startJD2.sh /opt/JDownloader/
lstat startJD2.sh: no such file or directory
LibreELEC:~/mydockerbuild #
```

**Comment by PlusMinus0** [comment]
Eh my bad. You need [this](https://raw.githubusercontent.com/PlusMinus0/headless-jd2-docker/master/startJD2.sh) shell script.

**Comment by Melf11** [comment]
okay, it seems to work, but in terminal i got this massage and it isn't going further.

```
25|Log.L.log 2/22/17 11:12:19 AM - SEVERE [ Log.L.log ] -> java.lang.ExceptionInInitializerError
	at jd.SecondLevelLaunch$12$1.run(SecondLevelLaunch.java:883)
Caused by: java.lang.RuntimeException: No Console Available!
	at org.appwork.console.ConsoleDialog.<init>(ConsoleDialog.java:56)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.start(MyJDownloaderController.java:102)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<init>(MyJDownloaderController.java:91)
	at org.jdownloader.api.myjdownloader.MyJDownloaderController.<clinit>(MyJDownloaderController.java:33)
	... 1 more

```
in Portainer is jolly_wozniak	with image plusminus/jdownloader2-headless:latest running. so just stop it an have a look at the config?

**Comment by Melf11** [comment]
it work :) one last question, is the org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json
already in the config folder? i might have overwritten the file, what should be the whole content?

and thanks a lot for your help!!!

**Comment by PlusMinus0** [comment]
Your credentials should suffice, create an empty file and paste them.
