### ISSUE TITLE
Out of disk space

### ISSUE THREAD

**Issue by mckraemer** [PlusMinus0/headless-jd2-docker#39]
Hi my problem is that I have around 250GB free space available. But JDownloader is stopping my downloads because it is out of memory. Size of download is around 40GB but it stops after ... around 8GB and says out of space.
Help is appreciated!

**Comment by PlusMinus0** [comment]
Are you storing the files in an external volume. IIRC, the maximum allowed size of a container is 20GB by default.

**Comment by mckraemer** [comment]
I am storing the files in my downloads folder within my home folder. MyJdownloader says it has only ~9GB available. Any ideas? I can post my docker run command if that would be helpful.

**Comment by mckraemer** [comment]
Sorry my fault, fixed it! Thank you for your time!
