### ISSUE TITLE
How to set "my.jdownloader" name?

### ISSUE THREAD

**Issue by the-hotmann** [PlusMinus0/headless-jd2-docker#41]
This instance does not let you set/customize the name of it when connecting to my.jdownloader.org.

![jDownloader](https://user-images.githubusercontent.com/17692860/103853146-aef83b00-50ad-11eb-8ea6-6b3ddc460c6a.PNG)
It always shows up as "JDOWNLOADER@JDOWNLOADER" which makes it hard to differenciate when two instances are active.

Is there a way (Environment variable etc ..) to to customoze the name it shows in my.jdownloader.org?

**Comment by PlusMinus0** [comment]
Edit this line
`  "devicename" : "JDownloader@myserver",`
in
`org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json`
